### ISSUE TITLE
Usage of global hyper::Client (via reqwest) leads to errors when executors exit

### ISSUE THREAD

**Issue by shepmaster** [ThouCheese/cloud-storage-rs#60] opened 2021-02-12 20:08 UTC
The current implementation has one global `Client`:

https://github.com/ThouCheese/cloud-storage-rs/blob/563124a02f7a2b1a04a419575bb936fa45461573/src/lib.rs#L118

While reusing a single hyper / reqwest client is a good idea to allow connection reuse, this implementation can lead to errors from hyper when the executor exits:

> dispatch dropped without returning error

This is explained in https://github.com/hyperium/hyper/issues/2112:

> The `Client` spawns background tasks to monitor the HTTP connection status, and if the executor drops it before it determines the connection was closed, it panics with that message

The easiest way to trigger this is to use something like `#[tokio::test]` with a large number of tests. Each test will spin up its own executor that ends when the test does.

Although less common, it's intended to be totally possible to have multiple executors in a "normal" execution, including starting and stopping them.

**Comment by shepmaster** [comment] 2021-02-12 20:12
I think the easiest + most backwards compatible solution would be to remove the global client and create one on demand instead.

More forward-looking, this crate could gain its own `State` / `Context` / `Client` abstraction. That would allow the user of the library to properly scope the lifetime of the `hyper::Client` to less than that of the executor.

This could even co-exist with the implicit global client to help with backwards compatibility — if `cloud_storage::Client.hyper_client` is `None` then fall back to a global value in the library.

**Comment by ThouCheese** [comment] 2021-02-13 19:21
Since we are on version 0.x I'd rather get the solution that is the most ergonomic/performant/correct than sacrifice any of the before for the sake of backwards compatibility. This seems to be a duplicate of #49 where I express some concerns and questions about how to best design this. If you have any ideas I'd love to hear them, since I haven't found or thought out which solution is the best.

**Comment by nhynes** [comment] 2021-03-28 17:05
why not have the user [pass a client in]https://docs.rs/cloud-storage-lite/0.1.0/cloud_storage_lite/struct.Client.html#method.new_with_client)? It's helpful if the `reqwest::Client` has some serious configuration on it like proxies 'n stuff.

**Comment by shepmaster** [comment] 2021-03-29 14:11
> why not have the user pass a client in

If #65 lands, then passing in a client should be straight-forward to add. The primary downside I see is that it moves an internal dependency to a public dependency, with all the knock-on effects involved.

**Comment by nhynes** [comment] 2021-03-29 14:27
> moves an internal dependency 

I like to think of it as dependency injection. There's no other popular http client implementation, so it's not like it's really all that internal. Most users will take the default configuration, sure, but for those who can't, you either fully replicate the configurability of `reqwest` or else take the `reqwest::Client` directly.

If `reqwest` weren't so popular (a monoculture), I'd agree more with knock-on effects.

**Closed** 2021-03-29 15:52 UTC
Labels: bug, enhancement

**Comment by ThouCheese** [comment] 2021-03-29 16:00
Even though it is the most popular http client library by far I don't think reqwest is ubiquitous enough to only support reqwest when going down this road. If we want to have dependency injection then cloud storage should provide a trait along the lines of `HttpClient` that just defines `perform_request` or something and then implement that trait for a couple of popular http clients. Then the user is no longer tied to Reqwest for http calls, and the user can pass in a trait object or use a polymorphic client for http calls. If the user then gets into version-hell (which I think is what @shepmaster is referring to) they can even wrap their version of reqwest into a struct and then implement `HttpClient` for that.

**Comment by shepmaster** [comment] 2021-03-29 16:50
> gets into version-hell

Yes, of multiple angles. On my understanding of semver, if `cloud-storage` 1.0 were to export `reqwest::Client` 1.0, then `reqwest` 2.0 comes out, `cloud-storage` must release it's own `2.0` in order to change the public-facing API.

The "right" solution is a shared abstraction — ideally some fundamental crate (that everyone agrees to use) defines the "get things from HTTP" trait. That doesn't currently exist, so crate-specific traits are the next best step. :-)

See also:

- [Why is a trait not implemented for a type that clearly has it implemented?](https://stackoverflow.com/q/44437123/155423)

**Comment by ThouCheese** [comment] 2021-03-30 11:40
I guess that if reqwest 2 got released we could include it as an optional dependency, and then hide it behind a feature flag. This would require adding a feature flag that includes reqwest 1, even when there is no reqwest 2 yet, and they would also we mutually exclusive/non-additive features, which Cargo does not like at all.

**Comment by nhynes** [comment] 2021-03-30 15:32
Why not make a `HttpClient` trait within this lib and impl that for `reqwest1::Client` and at some point `reqwest2::Client`? I wouldn't worry much about mutual exclusion. The worst that'll happen is compile times increase by a few %. The unused version will get DCE'd in a release build, so it won't exist where it counts.

**Comment by shepmaster** [comment] 2021-03-30 17:50
That's... [what ThouCheese already said](https://github.com/ThouCheese/cloud-storage-rs/issues/60#issuecomment-809503260):

> If we want to have dependency injection then cloud storage should provide a trait along the lines of `HttpClient` that just defines `perform_request` or something and then implement that trait for a couple of popular http clients

**Comment by nhynes** [comment] 2021-03-30 18:03
Sorry, I forgot the word _just_ (to distinguish from the extra work of feature flags). You know I can read, right?
